# version: 0.0
# os: linux
# files:
#   - source: /
#     destination: /home/ubuntu/eduapp
#     overwrite: true
# hooks:
#   AfterInstall:
#   #  - location: scripts/after_install.sh
#   #    timeout: 900
#      # runas: root
#    ApplicationStart:
#      - location: scripts/after_install.sh
#        timeout: 900
#   #     runas: root


version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/eduapp
    overwrite: true

hooks:
  AfterInstall:
    - location: scripts/deploy-react.sh
      timeout: 900       # 15 min
      runas: ubuntu
